spring:
  application:
    name: SecurityWithHttpSession
  datasource:
    url: jdbc:mysql://192.168.136.8:3306/security?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: wq666666
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.example.securitywithhttpsession.entity